#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then #-z true if string is null
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/sbin/apache2ctl -DFOREGROUND
fi
