#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then #-z true if string is null
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer
chmod -R ugo+w ./storage

#if [ $# -gt 0 ]; then
#    exec gosu $WWWUSER "$@"
#else
    exec /usr/sbin/apache2ctl -DFOREGROUND
    #exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
#fi
